---
title: "Story pitch - Sam Gauntt"
output: html_document
date: "2026-06-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Federal defense spending breakdown (2020-24) 

*By Sam Gauntt*

*May 31, 2026*

Under President Donald Trump’s requested federal budget for the next fiscal year, defense spending is slated to increase by 42%. Though this increase likely won’t be approved in its entirety, communities that receive defense funding or have major defense installations can still likely expect an economic boon. To predict what areas may see the bulk of this increase, I will use DOD data from 2020-2024 to determine where defense spending has historically been allocated, giving us an idea of which communities are most likely to benefit. An initial analysis of this data shows that Texas (\~\$257 billion), Virginia (\~\$216 billion) and California (\~\$186 billion) top the list by a significant margin. The state with the next highest amount of funding, Connecticut, still saw about \$80 billion less over the same time frame. Tarrant County alone, which encompasses Forth Worth in Texas, received more than \$120 billion. Overall, a handful of highly-funded counties, typically those with major military installations, make up a sizable amount of federal defense spending. By creating a geographic map of where this funding is going, and by joining this dataset with the Census to show per capita funding in addition to the raw totals, I will be able to provide a clearer picture of the defense funding environment and which communities could be the most impacted by future budget changes.
